# Generated by Django 5.2.13 on 2026-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('sensor', 'Sensor-Based (Model 1+2)'), ('meteo', 'Meteo-Based (Model 3)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('mq2', models.FloatField(blank=True, null=True)),
                ('mq4', models.FloatField(blank=True, null=True)),
                ('mq6', models.FloatField(blank=True, null=True)),
                ('mq8', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('source_lat', models.FloatField(blank=True, null=True)),
                ('source_lon', models.FloatField(blank=True, null=True)),
                ('gas_concentration', models.FloatField(blank=True, null=True)),
                ('stability_class', models.CharField(blank=True, max_length=5, null=True)),
                ('predicted_gas', models.CharField(blank=True, max_length=50, null=True)),
                ('danger_level', models.CharField(blank=True, max_length=20, null=True)),
                ('predicted_lat', models.FloatField(blank=True, null=True)),
                ('predicted_lon', models.FloatField(blank=True, null=True)),
                ('predicted_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('used_fallback', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
