# Generated by Django 5.2.13 on 2026-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionlog',
            old_name='gas_concentration',
            new_name='gas_ppm',
        ),
        migrations.RenameField(
            model_name='predictionlog',
            old_name='humidity',
            new_name='precip',
        ),
        migrations.RenameField(
            model_name='predictionlog',
            old_name='mq2',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='mq4',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='mq6',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='mq8',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='source_lat',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='source_lon',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='stability_class',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='temperature',
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='day_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='gas_type_input',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='danger_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='predicted_gas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='predicted_zone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='prediction_type',
            field=models.CharField(choices=[('sensor', 'Sensor / Model 1+2'), ('meteo', 'Real Meteo / Model 3')], max_length=10),
        ),
    ]
